---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: broker-role
rules:
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - bucketclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - bucketpools
    verbs:
      - get
      - list
      - watch
